project:
  type: website

website:
  title: "web"

  navbar:
    background: dark
    style: "floating"

    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: about

sidebar:
    - title: "Labs"
      border: true
      collapse-level: 1
      background: none
      style: "floating"
      contents:
        - text: "Create and publish by Quarto"
        - text: "---"  
        - section: "Lab#MD01-1"
          contents: 
            - introductiondevops.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

page-footer: 
    background: dark
    center: "it does not matter how slowly you go so long as you do not stop (Confucios)" 
    right: 
      - icon: github
        href: https://github.com/rarmero
      - icon: linkedin 
        href: https://es.linkedin.com/in/rafaelcarrion 