project:
  type: website

website:
  title: "App with web tecnologies"

  navbar:
    right:
      - href: index.qmd
        text: Home
      - sidebar:tasks
      - sidebar:projects
      - sidebar:labs
      - sidebar:theory
      - about.qmd

  sidebar:
    - id: "labs" 
      title: "Labs"
      border: true
      collapse-level: 1
      background: none
      style: "floating"
      contents:
        - text: "Labs"
        - section: "MarkUp Languages"
          contents:
           - "LabMD01-1.qmd"
           - section: List
             contents: 
              - "oil/ListOils.qmd"
              - "oil/ListOilsGrid.qmd"
              - "oil/ListOilsTable.qmd"
              - "oil/ListOilsCustom.qmd"
              - "oil/fileAttachment.qmd"
           - "LabMDObservable.qmd"
           - "LabMDResApi.qmd"
        - section: "Java Labs"
          contents: 
           - "LabSE00-1.qmd"
           - "LabSE01-1.qmd"
    - id: "tasks" 
      title: "Devops"
      contents:
        - text: "Devops"
        - text: "---"  
        - section: "Pipeline"
          contents:
           - "pipeline.qmd"
        - section: "Kubernettes"
          contents:
           - "Task1.qmd"
        - section: "Quarto docker"
          contents:
           - "Task2.qmd"

    - id: "projects" 
      title: "Projects"
      collapse-level: 1
      background: none
      style: "floating"
      contents:
        - text: "Projects"
        - text: "---"  
        - section: "Mobility"
          contents:
           - "Project1.qmd"
           - "Project1b.qmd"
        - section: "Static application security testing"
          contents:
           - "Project2.qmd"
           - "Project2Management.qmd"
           - "javasonarqube.qmd"
        - section: "Dynamic application security testing"
          contents:
           - "Project3.qmd"
        - section: "Project4"
          contents:
           - "testing.qmd" 

    - id: "theory" 
      title: "Theory"
      contents:
        - text: "Theory"
        - text: "---"
        - section: "Documentation"
          contents:
           - "Theory1.qmd"      
        - section: "Patterns"
          contents:
           - "patterns1.qmd"
           - "PatternCommand.qmd"    

  page-footer: 
    background: dark
    center: "it does not matter how slowly you go so long as you do not stop (Confucios)" 
    right: 
      - icon: github
        href: https://github.com/rarmero
      - icon: linkedin 
        href: https://es.linkedin.com/in/rafaelcarrion 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

