---
title: "Internships"
subtitle : "Company relative to develop a software platform to manage fleets by GPS"
---

# Onboarding


> Objetive:
>
> A junior or sernior software developer would be read the document,
> explained below and undestarnd the bussiness model, kwnow the practices on the company and develop software.

## Tools: 

- IDE Visual Studio with c#
- GIT
- SQL Management Studio
- Postman
- Azure Devops: boards, repository, Pipelines, 
- Workspace Google


## Enviroment Configuration 

- access to network
- git user
- connection string to database
- ip's servers.

TODO: explain how

## Arquitecture

- RestFul API
- Microservices
- Multilayer
- Entity Framework
- Patterns : DI, Mediator, Repository

## Techniques

- SOLID
- LINQ
- CQRS with MediatR
- Mapping with Dapper
- Event bus with RabbitMQ

## References

[Microservices](https://learn.microsoft.com/en-us/dotnet/architecture/microservices/){.external}

## Procedures

- Git: creating branches by US


TODO: explain how

# Bussines model

- Management fleets by gps.
- Entities: 
    + base
    + companymaster
    + company
    + client
    + employe
    + product
    + order
    + fleet
    + vehicle
    + insurance
    + operator

- Diagram class

<div class="mermaidContent">

```{mermaid}
classDiagram

class CompanyMaster 
class Company 
class Customer
class Employee 
class Insurance
class Fleet
class Base
class Product
class Vehicle
class Order
class Operator

CompanyMaster <|-- Base: Aggregation
CompanyMaster <|-- Product: Aggregation
CompanyMaster <|-- Company: Aggregation
Company <|-- Customer: Aggregation
Company <|-- Employee: Aggregation
Company <|-- Fleet: Aggregation
Customer <|-- Insurance: Aggregation
Fleet <|-- Vehicle: Aggregation
Order <|-- Company: Aggregation
Order <|-- Operator: Aggregation
Operator <|-- Employee
Order <|-- Fleet: Aggregation
```
</div>

## Features

company, clients, providers, orders, employees, schedule control, job signing

Definition of the terms according the point of view.


## Apliying Business model to develop sotware

- List microservices
- Uses Cases.
- Query logic.

# Vocabulary

- flotas
- pedido
- servicio
- facturaci贸n
- cobro
- orden
- supervisor
- empleado
- recorrido
- distancias
- tarifas

# functions

- Localizar flota.
- Asignar choferes a ordenes de trabajo.
- Fichajes.
- Facturaci贸n.
- Informes de la actividad de la fota.
- Informes de la facturaci贸n a los clientes.
- Comisiones y liquidaciones.
- Seguimiento del pedido.
- Integraci贸n API.
